# Generated by Django 5.1a1 on 2024-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(max_length=32)),
                ('park_name', models.CharField(max_length=32)),
                ('jinru_date', models.CharField(max_length=32)),
                ('chuqu_date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
            ],
        ),
    ]
