# Generated by Django 5.1a1 on 2024-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseboard_sn', models.CharField(max_length=100)),
                ('bios_sn', models.CharField(max_length=100)),
                ('cpu_id', models.CharField(max_length=100)),
                ('cpu_name', models.CharField(max_length=100)),
                ('cs_uuid', models.CharField(max_length=100)),
                ('disk_sn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_key', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('license_date', models.DateTimeField()),
                ('is_used', models.BooleanField()),
                ('valid_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField()),
                ('is_used', models.BooleanField()),
                ('license_key', models.CharField(max_length=100)),
            ],
        ),
    ]
