# Generated by Django 5.1a1 on 2024-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_key_license_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='key',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='key',
            name='license_date',
        ),
        migrations.RemoveField(
            model_name='key',
            name='license_to',
        ),
        migrations.RemoveField(
            model_name='key',
            name='valid_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createtime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='key',
            name='valid_key',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_key',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=31),
        ),
    ]
