# Generated by Django 5.1a1 on 2024-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_key_create_date_remove_key_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='valid_days',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='valid_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=32),
        ),
    ]
