# Generated by Django 5.1a1 on 2024-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_key_is_used_key_valid_days_user_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='create_date',
            field=models.DateTimeField(default='2020-1-1', null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='license_date',
            field=models.DateTimeField(default='2020-1-1', null=True),
        ),
    ]
