# Generated by Django 5.1a1 on 2024-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_key_create_date_key_license_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
