# Generated by Django 5.1a1 on 2024-06-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_createtime_alter_key_license_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='license_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
