# Generated by Django 5.1a1 on 2024-06-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_key_license_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='license_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
