# Generated by Django 5.1a1 on 2024-06-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_key_license_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
