# Generated by Django 5.1a1 on 2024-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField(null=True)),
            ],
        ),
    ]
