# Generated by Django 5.1a1 on 2024-06-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
