# Generated by Django 5.1a1 on 2024-08-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_board_sn', models.CharField(max_length=300)),
                ('bios_sn', models.CharField(max_length=300)),
                ('cpu_id', models.CharField(max_length=300)),
                ('cpu_name', models.CharField(max_length=300)),
                ('cs_uuid', models.CharField(max_length=300)),
                ('disk_sn', models.CharField(max_length=300)),
            ],
        ),
    ]
